// Idempotent: backs up to .orig.jpg on first run, always re-encodes from the .orig
// so re-running with different params is safe.
import sharp from "sharp";
import fs from "node:fs/promises";
import path from "node:path";

const PUBLIC = path.resolve("public");

// Recursively find all files in a directory
async function getFiles(dir) {
  const dirents = await fs.readdir(dir, { withFileTypes: true });
  const files = await Promise.all(dirents.map((dirent) => {
    const res = path.resolve(dir, dirent.name);
    return dirent.isDirectory() ? getFiles(res) : res;
  }));
  return Array.prototype.concat(...files);
}

const allFiles = await getFiles(PUBLIC);
const TARGETS = allFiles
  .filter(file => file.match(/\.(jpe?g)$/i) && !file.endsWith(".orig.jpg"))
  .map(file => path.relative(PUBLIC, file).replace(/\\/g, '/'));

const MAX_WIDTH = 1600;
const QUALITY = 78;
const BLUR_SIZE = 20;

const placeholders = {};

console.log(`Found ${TARGETS.length} images to optimize.`);

for (const rel of TARGETS) {
  const abs = path.join(PUBLIC, rel);
  const orig = abs.replace(/\.jpe?g$/i, ".orig.jpg");

  try {
    await fs.access(orig);
  } catch {
    await fs.copyFile(abs, orig);
    console.log(`backup → ${path.basename(orig)}`);
  }

  const buf = await sharp(orig)
    .rotate()
    .resize({ width: MAX_WIDTH, withoutEnlargement: true })
    .jpeg({ quality: QUALITY, mozjpeg: true, progressive: true })
    .toBuffer();
  await fs.writeFile(abs, buf);

  const blur = await sharp(orig)
    .rotate()
    .resize(BLUR_SIZE, BLUR_SIZE, { fit: "inside" })
    .jpeg({ quality: 35 })
    .toBuffer();
  placeholders[`/${rel}`] = `data:image/jpeg;base64,${blur.toString("base64")}`;

  const finalSize = (await fs.stat(abs)).size;
  console.log(`repack ${rel} → ${(finalSize / 1024).toFixed(0)} KB`);
}

const out =
  `// Auto-generated by scripts/optimize-images.mjs — do not edit by hand.\n` +
  `export const blurPlaceholders: Record<string, string> = ${JSON.stringify(placeholders, null, 2)};\n`;
await fs.mkdir(path.resolve("src/data"), { recursive: true });
await fs.writeFile(path.resolve("src/data/blur-placeholders.ts"), out);

console.log(`\nDone. ${TARGETS.length} images optimized, blur lookup written.`);
