// Idempotent: backs up to .orig.jpg on first run, always re-encodes from the .orig
// so re-running with different params is safe.
import sharp from "sharp";
import fs from "node:fs/promises";
import path from "node:path";

const PUBLIC = path.resolve("public");
const TARGETS = [
  "images/IMG_1453.jpg",
  "images/thumbnail/thumbnail-mother.jpg",
  "images/thumbnail/thumbnail-headmaster.jpg",
  "images/thumbnail/thumbnail-victoria.jpg",
  "images/thumbnail/thumbnail-afriyie.jpg",
  "volunteer1.jpg",
  "volunteer2.jpg",
];

const MAX_WIDTH = 1600;
const QUALITY = 78;
const BLUR_SIZE = 20;

const placeholders = {};

for (const rel of TARGETS) {
  const abs = path.join(PUBLIC, rel);
  const orig = abs.replace(/\.jpe?g$/i, ".orig.jpg");

  try {
    await fs.access(orig);
  } catch {
    await fs.copyFile(abs, orig);
    console.log(`backup → ${path.basename(orig)}`);
  }

  const buf = await sharp(orig)
    .rotate()
    .resize({ width: MAX_WIDTH, withoutEnlargement: true })
    .jpeg({ quality: QUALITY, mozjpeg: true, progressive: true })
    .toBuffer();
  await fs.writeFile(abs, buf);

  const blur = await sharp(orig)
    .rotate()
    .resize(BLUR_SIZE, BLUR_SIZE, { fit: "inside" })
    .jpeg({ quality: 35 })
    .toBuffer();
  placeholders[`/${rel}`] = `data:image/jpeg;base64,${blur.toString("base64")}`;

  const finalSize = (await fs.stat(abs)).size;
  console.log(`repack ${rel} → ${(finalSize / 1024).toFixed(0)} KB`);
}

const out =
  `// Auto-generated by scripts/optimize-images.mjs — do not edit by hand.\n` +
  `export const blurPlaceholders: Record<string, string> = ${JSON.stringify(placeholders, null, 2)};\n`;
await fs.mkdir(path.resolve("src/data"), { recursive: true });
await fs.writeFile(path.resolve("src/data/blur-placeholders.ts"), out);

console.log(`\nDone. ${TARGETS.length} images optimized, blur lookup written.`);
